{"name": "Error when creating an order with an incorrect ingredient hash", "status": "passed", "start": 1713109044530, "stop": 1713109044902, "uuid": "8386b3d9-f7d1-4dc8-87b0-3c03786af047", "historyId": "378590a320d57e7ca253d39d949023c5", "testCaseId": "378590a320d57e7ca253d39d949023c5", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_incorrect_hash_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "System-Product"}, {"name": "thread", "value": "31366-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}